---
- name: CREATE AND EXECUTE SCRIPTS
  hosts: FortiManager
  connection: httpapi
  gather_facts: False

  tasks:
    - name: CREATE SCRIPT
      fmgr_script:
        adom: "ansible"
        script_name: "TestScript"
        script_type: "cli"
        script_target: "remote_device"
        script_description: "Create by Ansible"
        script_content: "get system status"

    - name: EXECUTE SCRIPT
      fmgr_script:
        adom: "ansible"
        script_name: "TestScript"
        mode: "execute"
        script_scope: "FGT1"

    - name: DELETE SCRIPT
      fmgr_script:
        adom: "ansible"
        script_name: "TestScript"
        mode: "delete"
